# Generated by Django 4.1.5 on 2023-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_name_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(null=True, upload_to='books'),
        ),
    ]
