# Generated by Django 4.1.5 on 2023-01-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_page_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_id',
        ),
    ]
