# Generated by Django 4.1.5 on 2023-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_author_id_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(null=True, upload_to='media/books'),
        ),
    ]
