# Generated by Django 4.1.5 on 2023-01-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(null=True, upload_to='books'),
        ),
    ]
